name: ci

on:
  push:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push amd64
        uses: docker/build-push-action@v3.1.1
        with:
          platforms: linux/amd64
          push: true
          tags: jeanluc162/openmultiplayer-server:${{ github.ref_name }}
          file: Dockerfile.amd64
      -
        name: Build and push arm64
        uses: docker/build-push-action@v3.1.1
        with:
          platforms: linux/arm64
          push: true
          tags: jeanluc162/openmultiplayer-server:${{ github.ref_name }}
          file: Dockerfile.arm64
